# =============================================================================
# PostgreSQL Exporter Template
# =============================================================================
# Add this service to your PostgreSQL docker-compose.yml to enable monitoring
#
# Steps:
#   1. Copy this service definition to your postgres docker-compose.yml
#   2. Update the environment variables to match your setup
#   3. Start the exporter: docker compose up -d postgres-exporter
#   4. Register with Prometheus:
#      ./observability/scripts/manage-targets.sh add postgres \
#        --name my-database \
#        --host host.docker.internal \
#        --port 9187
# =============================================================================

services:
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: ${EXPORTER_NAME:-postgres-exporter}
    restart: unless-stopped
    environment:
      - TZ=UTC
      # Option 1: Use DATA_SOURCE_NAME (connection string)
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}?sslmode=disable
      # Option 2: Use separate variables (uncomment below, comment above)
      # - DATA_SOURCE_URI=${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}?sslmode=disable
      # - DATA_SOURCE_USER=${POSTGRES_USER:-postgres}
      # - DATA_SOURCE_PASS=${POSTGRES_PASSWORD}
    ports:
      # Expose on host - use unique port for each database
      # postgres-single: 9187
      # postgres-master: 9188
      # postgres-slave:  9189
      # timescaledb:     9190
      - "127.0.0.1:${EXPORTER_PORT:-9187}:9187"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
        reservations:
          cpus: "0.1"
          memory: 32M
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9187/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Use same network as your PostgreSQL
    networks:
      - default
    depends_on:
      - postgres  # Change to your postgres service name
