#!/bin/bash
# =============================================================================
# Garage One-Click Setup
# =============================================================================
# Fully automated setup: config, secrets, start, layout
# Usage: ./setup.sh
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

echo ""
echo "=============================================="
echo "  Garage S3 Storage - Setup"
echo "=============================================="
echo ""

# Step 1: Create .env if not exists
if [[ ! -f ".env" ]]; then
    log_info "Creating .env from template..."
    cp .env.example .env
fi

# Load current env to check secrets
set -a
source .env
set +a

# Validate and regenerate secrets if needed
NEED_SECRET_UPDATE=false

# RPC secret must be exactly 64 hex characters (32 bytes)
if [[ -z "$GARAGE_RPC_SECRET" ]] || [[ ${#GARAGE_RPC_SECRET} -ne 64 ]]; then
    log_info "Generating new RPC secret (must be 64 hex chars)..."
    RPC_SECRET=$(openssl rand -hex 32)
    NEED_SECRET_UPDATE=true
fi

if [[ -z "$GARAGE_ADMIN_TOKEN" ]]; then
    log_info "Generating new admin token..."
    ADMIN_TOKEN=$(openssl rand -base64 32 | tr -d '\n')
    NEED_SECRET_UPDATE=true
fi

if [[ "$NEED_SECRET_UPDATE" == "true" ]]; then
    log_info "Updating secrets in .env..."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        [[ -n "${RPC_SECRET:-}" ]] && sed -i '' "s|^GARAGE_RPC_SECRET=.*|GARAGE_RPC_SECRET=${RPC_SECRET}|" .env
        [[ -n "${ADMIN_TOKEN:-}" ]] && sed -i '' "s|^GARAGE_ADMIN_TOKEN=.*|GARAGE_ADMIN_TOKEN=${ADMIN_TOKEN}|" .env
        [[ -n "${ADMIN_TOKEN:-}" ]] && sed -i '' "s|^GARAGE_METRICS_TOKEN=.*|GARAGE_METRICS_TOKEN=${ADMIN_TOKEN}|" .env
    else
        [[ -n "${RPC_SECRET:-}" ]] && sed -i "s|^GARAGE_RPC_SECRET=.*|GARAGE_RPC_SECRET=${RPC_SECRET}|" .env
        [[ -n "${ADMIN_TOKEN:-}" ]] && sed -i "s|^GARAGE_ADMIN_TOKEN=.*|GARAGE_ADMIN_TOKEN=${ADMIN_TOKEN}|" .env
        [[ -n "${ADMIN_TOKEN:-}" ]] && sed -i "s|^GARAGE_METRICS_TOKEN=.*|GARAGE_METRICS_TOKEN=${ADMIN_TOKEN}|" .env
    fi
    # Reload after update
    source .env
else
    log_info ".env secrets are valid, skipping..."
fi

# Step 2: Create directories
log_info "Creating directories..."
mkdir -p config data meta scripts

# Step 3: Generate garage.toml
log_info "Generating garage.toml..."

cat > config/garage.toml << EOF
# Auto-generated by setup.sh - $(date)
data_dir = "/var/lib/garage/data"
metadata_dir = "/var/lib/garage/meta"
db_engine = "sqlite"

replication_factor = ${GARAGE_REPLICATION_FACTOR:-1}
block_size = ${GARAGE_BLOCK_SIZE:-1048576}
compression_level = ${GARAGE_COMPRESSION_LEVEL:-1}
metadata_auto_snapshot_interval = "6h"

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "${GARAGE_RPC_PUBLIC_ADDR:-garage:3901}"
rpc_secret = "${GARAGE_RPC_SECRET}"

[s3_api]
api_bind_addr = "[::]:3900"
s3_region = "${GARAGE_S3_REGION:-garage}"
root_domain = "${GARAGE_S3_ROOT_DOMAIN:-.s3.garage.localhost}"

[s3_web]
bind_addr = "[::]:3902"
root_domain = "${GARAGE_WEB_ROOT_DOMAIN:-.web.garage.localhost}"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "${GARAGE_ADMIN_TOKEN}"
metrics_token = "${GARAGE_METRICS_TOKEN:-$GARAGE_ADMIN_TOKEN}"
EOF

# Step 4: Start Garage
log_info "Starting Garage..."
docker compose up -d garage

# Step 5: Wait for Garage to be ready
log_info "Waiting for Garage to start..."
sleep 3

for i in {1..30}; do
    if docker exec garage /garage status &>/dev/null; then
        break
    fi
    sleep 1
done

# Step 6: Setup layout
log_info "Setting up cluster layout..."

NODE_ID=$(docker exec garage /garage status 2>/dev/null | grep -oE '[a-f0-9]{64}' | head -1)

if [[ -n "$NODE_ID" ]]; then
    # Check if layout already exists
    LAYOUT_CHECK=$(docker exec garage /garage layout show 2>&1 || true)

    if echo "$LAYOUT_CHECK" | grep -q "No nodes"; then
        docker exec garage /garage layout assign \
            --zone "${GARAGE_ZONE:-dc1}" \
            --capacity "${GARAGE_CAPACITY:-100G}" \
            "$NODE_ID" 2>/dev/null

        docker exec garage /garage layout apply --version 1 2>/dev/null
        log_info "Layout configured"
    else
        log_info "Layout already configured"
    fi
else
    log_warn "Could not get node ID, run setup-layout.sh manually"
fi

# Done
echo ""
echo "=============================================="
echo -e "  ${GREEN}Setup Complete!${NC}"
echo "=============================================="
echo ""
echo "Garage is running at:"
echo "  S3 API:    http://localhost:${GARAGE_S3_API_PORT:-3900}"
echo "  Admin:     http://localhost:${GARAGE_ADMIN_PORT:-3903}"
echo ""
echo "Next steps:"
echo "  1. Create a bucket:  ./scripts/manage.sh quick-setup myapp"
echo "  2. View status:      ./scripts/manage.sh status"
echo ""
echo "Web UI (optional):"
echo "  docker compose --profile webui up -d"
echo "  http://localhost:${GARAGE_WEB_UI_PORT:-3909}"
echo "  User: ${GARAGE_WEB_UI_USER:-admin}"
echo ""
