#!/bin/bash

#######################################
# VPS Initial Setup Script for Production
# Run this FIRST when you get a fresh VPS
#
# This script ONLY handles system hardening:
#   - SSH hardening (port, security settings)
#   - Firewall configuration
#   - Fail2ban / brute-force protection
#   - System limits & optimizations
#   - Automatic security updates
#
# User management is handled separately by add-user.sh
# Run add-user.sh AFTER docker-install.sh to create Infra Admin
#######################################

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   log_error "This script must be run as root"
   log_info "Run: sudo bash vps-initial-setup.sh"
   exit 1
fi

# Get the actual user who invoked sudo
CURRENT_USER="${SUDO_USER:-$USER}"
CURRENT_USER_HOME=$(eval echo ~$CURRENT_USER)

echo "=========================================="
echo "  VPS Initial Setup - System Hardening"
echo "=========================================="
echo ""
log_info "Current user: $CURRENT_USER"
echo ""

#######################################
# Configuration
#######################################
echo -e "${CYAN}SSH Configuration:${NC}"
read -p "Enter SSH port (default 22, recommended 2222): " SSH_PORT
SSH_PORT=${SSH_PORT:-2222}

echo ""
echo -e "${CYAN}SSH Key Setup (optional):${NC}"
echo "If your current user already has SSH key configured, you can skip this."
read -p "Add/update SSH public key for $CURRENT_USER? (y/n): " SETUP_SSH_KEY

SSH_PUBLIC_KEY=""
if [[ "$SETUP_SSH_KEY" == "y" ]]; then
    echo "Paste your SSH public key (starts with ssh-rsa or ssh-ed25519):"
    read SSH_PUBLIC_KEY
fi

echo ""
echo -e "${CYAN}Root Login:${NC}"
read -p "Disable root SSH login? (recommended if you have sudo user) (y/n): " DISABLE_ROOT
DISABLE_ROOT=${DISABLE_ROOT:-y}

#######################################
# Detect OS
#######################################
log_step "Detecting operating system..."
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
    log_info "Detected: $OS"
else
    log_error "Cannot detect OS"
    exit 1
fi

#######################################
# Update system
#######################################
log_step "Updating system packages..."
if [[ "$OS" == "ubuntu" ]] || [[ "$OS" == "debian" ]]; then
    apt-get update
    apt-get upgrade -y
    apt-get install -y curl wget vim git ufw fail2ban unattended-upgrades
elif [[ "$OS" == "centos" ]] || [[ "$OS" == "rhel" ]] || [[ "$OS" == "amzn" ]] || [[ "$OS" == "ol" ]]; then
    yum update -y
    yum install -y epel-release || true
    yum install -y curl wget vim git firewalld policycoreutils-python-utils audit
    yum install -y fail2ban fail2ban-systemd 2>/dev/null || log_warn "fail2ban not available"
fi
log_info "System updated"

#######################################
# Setup SSH key for current user (if requested)
#######################################
if [[ -n "$SSH_PUBLIC_KEY" ]]; then
    log_step "Setting up SSH key for $CURRENT_USER"

    mkdir -p "$CURRENT_USER_HOME/.ssh"

    # Check if key already exists
    if grep -q "$SSH_PUBLIC_KEY" "$CURRENT_USER_HOME/.ssh/authorized_keys" 2>/dev/null; then
        log_warn "SSH key already exists"
    else
        echo "$SSH_PUBLIC_KEY" >> "$CURRENT_USER_HOME/.ssh/authorized_keys"
        log_info "SSH key added"
    fi

    chmod 700 "$CURRENT_USER_HOME/.ssh"
    chmod 600 "$CURRENT_USER_HOME/.ssh/authorized_keys"
    chown -R "$CURRENT_USER:$CURRENT_USER" "$CURRENT_USER_HOME/.ssh"
fi

#######################################
# Harden SSH configuration
#######################################
log_step "Hardening SSH configuration..."

# Backup original config
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%F_%T)

# Create hardening config directory if needed
mkdir -p /etc/ssh/sshd_config.d

# Determine root login setting
if [[ "$DISABLE_ROOT" == "y" ]]; then
    ROOT_LOGIN="no"
else
    ROOT_LOGIN="prohibit-password"
fi

# Determine password auth (disable if SSH key is set up)
if [[ -n "$SSH_PUBLIC_KEY" ]] || [[ -f "$CURRENT_USER_HOME/.ssh/authorized_keys" ]]; then
    PASSWORD_AUTH="no"
    log_info "SSH key detected - disabling password authentication"
else
    PASSWORD_AUTH="yes"
    log_warn "No SSH key detected - keeping password authentication enabled"
fi

# Apply hardened SSH settings
cat > /etc/ssh/sshd_config.d/hardening.conf <<EOF
# SSH Hardening Configuration
# Generated by vps-initial-setup.sh on $(date)

Port $SSH_PORT
PermitRootLogin $ROOT_LOGIN
PasswordAuthentication $PASSWORD_AUTH
PubkeyAuthentication yes
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding no
PrintMotd no
AcceptEnv LANG LC_*
ClientAliveInterval 300
ClientAliveCountMax 2
MaxAuthTries 3
MaxSessions 10
Protocol 2
EOF

# Configure SELinux for custom SSH port (RHEL-based systems)
if [[ "$OS" == "centos" ]] || [[ "$OS" == "rhel" ]] || [[ "$OS" == "amzn" ]] || [[ "$OS" == "ol" ]]; then
    if [[ "$SSH_PORT" != "22" ]]; then
        log_step "Configuring SELinux for SSH port $SSH_PORT..."
        if command -v semanage &> /dev/null; then
            if ! semanage port -l | grep -q "ssh_port_t.*$SSH_PORT"; then
                semanage port -a -t ssh_port_t -p tcp $SSH_PORT 2>/dev/null || \
                semanage port -m -t ssh_port_t -p tcp $SSH_PORT 2>/dev/null || \
                log_warn "Could not configure SELinux for port $SSH_PORT"
            fi
            log_info "SELinux configured for SSH port $SSH_PORT"
        else
            log_warn "semanage not available, SELinux may block SSH on port $SSH_PORT"
        fi
    fi
fi

# Restart SSH
systemctl restart sshd || systemctl restart ssh

log_info "SSH hardened - Port: $SSH_PORT"

#######################################
# Configure firewall
#######################################
log_step "Configuring firewall..."

if [[ "$OS" == "ubuntu" ]] || [[ "$OS" == "debian" ]]; then
    ufw --force reset
    ufw default deny incoming
    ufw default allow outgoing
    ufw allow $SSH_PORT/tcp comment 'SSH'
    ufw allow 80/tcp comment 'HTTP'
    ufw allow 443/tcp comment 'HTTPS'
    ufw --force enable
    log_info "UFW firewall configured"

elif [[ "$OS" == "centos" ]] || [[ "$OS" == "rhel" ]] || [[ "$OS" == "amzn" ]] || [[ "$OS" == "ol" ]]; then
    systemctl start firewalld
    systemctl enable firewalld
    firewall-cmd --permanent --zone=public --add-port=$SSH_PORT/tcp
    firewall-cmd --permanent --zone=public --add-service=http
    firewall-cmd --permanent --zone=public --add-service=https
    firewall-cmd --reload
    log_info "Firewalld configured"
fi

#######################################
# Configure SSH Protection (fail2ban)
#######################################
log_step "Configuring SSH brute-force protection..."

if command -v fail2ban-server &> /dev/null; then
    cat > /etc/fail2ban/jail.local <<EOF
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3

[sshd]
enabled = true
port = $SSH_PORT
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
EOF

    # For RHEL-based systems
    if [[ "$OS" == "centos" ]] || [[ "$OS" == "rhel" ]] || [[ "$OS" == "amzn" ]] || [[ "$OS" == "ol" ]]; then
        sed -i 's|/var/log/auth.log|/var/log/secure|' /etc/fail2ban/jail.local
    fi

    systemctl enable fail2ban
    systemctl restart fail2ban
    log_info "Fail2ban configured (3 failed attempts = 1 hour ban)"
else
    log_warn "fail2ban not available"
    if [[ "$OS" == "ol" ]]; then
        log_info "Oracle Linux 9: SSH protected by MaxAuthTries=3"
    fi
fi

#######################################
# Enable automatic security updates
#######################################
log_step "Configuring automatic security updates..."

if [[ "$OS" == "ubuntu" ]] || [[ "$OS" == "debian" ]]; then
    cat > /etc/apt/apt.conf.d/50unattended-upgrades <<EOF
Unattended-Upgrade::Allowed-Origins {
    "\${distro_id}:\${distro_codename}-security";
};
Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
EOF

    cat > /etc/apt/apt.conf.d/20auto-upgrades <<EOF
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF
    log_info "Automatic security updates enabled"

elif [[ "$OS" == "centos" ]] || [[ "$OS" == "rhel" ]] || [[ "$OS" == "amzn" ]] || [[ "$OS" == "ol" ]]; then
    if command -v dnf &> /dev/null; then
        yum install -y dnf-automatic
        sed -i 's/^apply_updates = .*/apply_updates = yes/' /etc/dnf/automatic.conf 2>/dev/null || true
        sed -i 's/^upgrade_type = .*/upgrade_type = security/' /etc/dnf/automatic.conf 2>/dev/null || true
        systemctl enable dnf-automatic.timer
        systemctl start dnf-automatic.timer
        log_info "Automatic security updates enabled (dnf-automatic)"
    else
        yum install -y yum-cron
        systemctl enable yum-cron
        systemctl start yum-cron
        log_info "Automatic security updates enabled (yum-cron)"
    fi
fi

#######################################
# Set timezone to UTC
#######################################
log_step "Setting timezone to UTC..."
timedatectl set-timezone UTC
log_info "Timezone set to UTC"

#######################################
# Configure system limits
#######################################
log_step "Configuring system limits for production..."

# Check if limits already configured
if ! grep -q "# Production system limits" /etc/security/limits.conf; then
    cat >> /etc/security/limits.conf <<EOF

# Production system limits
* soft nofile 65536
* hard nofile 65536
* soft nproc 32768
* hard nproc 32768
EOF
fi

# Check if sysctl already configured
if ! grep -q "# Network optimizations" /etc/sysctl.conf; then
    cat >> /etc/sysctl.conf <<EOF

# Network optimizations
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15

# Security
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Memory
vm.swappiness = 10
vm.vfs_cache_pressure = 50
EOF
fi

sysctl -p >/dev/null 2>&1 || true
log_info "System limits configured"

#######################################
# Create helpful aliases
#######################################
log_step "Setting up helpful aliases..."

if ! grep -q "# Infrastructure aliases" "$CURRENT_USER_HOME/.bashrc"; then
    cat >> "$CURRENT_USER_HOME/.bashrc" <<'EOF'

# Infrastructure aliases
alias dps='docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"'
alias dlog='docker logs -f'
alias dlogs='docker compose logs -f'
alias dstop='docker stop $(docker ps -q) 2>/dev/null || echo "No containers running"'
alias dclean='docker system prune -af'
alias ports='sudo ss -tulpn | grep LISTEN'
alias meminfo='free -h'
alias diskinfo='df -h | grep -v tmpfs'
EOF
    chown "$CURRENT_USER:$CURRENT_USER" "$CURRENT_USER_HOME/.bashrc"
    log_info "Helpful aliases added"
fi

#######################################
# Display summary
#######################################
HOSTNAME=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "YOUR_SERVER_IP")

echo ""
echo "=========================================="
log_info "System Hardening Complete!"
echo "=========================================="
echo ""
echo -e "${CYAN}Configuration Summary:${NC}"
echo "  - SSH port: $SSH_PORT"
echo "  - Root login: $([[ "$ROOT_LOGIN" == "no" ]] && echo "DISABLED" || echo "Key-only")"
echo "  - Password auth: $([[ "$PASSWORD_AUTH" == "no" ]] && echo "DISABLED (key-only)" || echo "ENABLED")"
echo "  - Firewall: ENABLED (ports: $SSH_PORT, 80, 443)"
if command -v fail2ban-server &> /dev/null; then
    echo "  - Fail2ban: ENABLED"
else
    echo "  - SSH protection: MaxAuthTries=3"
fi
echo "  - Auto updates: ENABLED"
echo "  - Timezone: UTC"
echo ""

echo -e "${YELLOW}CRITICAL: Test SSH connection in a NEW terminal:${NC}"
echo ""
echo "  ssh -p $SSH_PORT $CURRENT_USER@$HOSTNAME"
echo ""
echo -e "${YELLOW}Keep this terminal open until you verify access!${NC}"
echo ""

echo "=========================================="
echo -e "${CYAN}Next Steps:${NC}"
echo "=========================================="
echo ""
echo "1. Test SSH in new terminal (command above)"
echo ""
echo "2. Install Docker:"
echo "   sudo bash scripts/docker-install.sh"
echo ""
echo "3. Create your Infra Admin user (full permissions):"
echo "   sudo bash scripts/add-user.sh"
echo "   -> Select type 3 (Infra Admin)"
echo ""
echo "4. Setup infrastructure:"
echo "   cd /opt/infra && ./setup.sh"
echo ""
echo "=========================================="
echo -e "${CYAN}User Types (add-user.sh):${NC}"
echo "=========================================="
echo "  1) Developer   - SSH only (deploy apps)"
echo "  2) DevOps      - SSH + sudo (manage system)"
echo "  3) Infra Admin - SSH + sudo + docker (FULL control)"
echo "  4) Tunnel Only - SSH tunnel only (DB access)"
echo ""
echo "=========================================="
